// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twilioconnector.actions;

import java.util.HashMap;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.twilio.sdk.TwilioRestClient;
import com.twilio.sdk.resource.factory.CallFactory;
import com.twilio.sdk.resource.instance.Account;
import com.twilio.sdk.resource.instance.Call;

/**
 * Message - The body of your SMS message
 * 
 * To - Telephone number to send the message to.
 * 
 * From - A valid phone number in your Twilio account.
 */
public class MakeCall extends CustomJavaAction<Boolean>
{
	private String Account_SID;
	private String Account_token;
	private String Url;
	private String From;
	private String To;

	public MakeCall(IContext context, String Account_SID, String Account_token, String Url, String From, String To)
	{
		super(context);
		this.Account_SID = Account_SID;
		this.Account_token = Account_token;
		this.Url = Url;
		this.From = From;
		this.To = To;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if(this.Account_SID == null || this.Account_SID.isEmpty() || this.Account_token == null || this.Account_token.isEmpty()) {
			throw new IllegalArgumentException("Account SID and/or token shouldn't be empty");
		}
		
		TwilioRestClient client = new TwilioRestClient(this.Account_SID , this.Account_token);

		final Account mainAccount = client.getAccount();
		
		final CallFactory callFactory = mainAccount.getCallFactory();
	    final Map<String, String> callParams = new HashMap<String, String>();
	    callParams.put("To", this.To); 
	    callParams.put("From", this.From);  
	    callParams.put("Url", this.Url);
	    final Call call = callFactory.create(callParams);
	    
	    return true;
	    
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "MakeCall";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
