// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilio.proxies;

public class MessageListResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageListResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Twilio.MessageListResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		first_page_uri("first_page_uri"),
		end("end"),
		previous_page_uri("previous_page_uri"),
		uri("uri"),
		page_size("page_size"),
		start("start"),
		next_page_uri("next_page_uri"),
		num_pages("num_pages"),
		total("total"),
		last_page_uri("last_page_uri"),
		page("page"),
		messages("Twilio.messages");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MessageListResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Twilio.MessageListResponse"));
	}

	protected MessageListResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageListResponseMendixObject)
	{
		if (messageListResponseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Twilio.MessageListResponse", messageListResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Twilio.MessageListResponse");

		this.messageListResponseMendixObject = messageListResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MessageListResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twilio.proxies.MessageListResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilio.proxies.MessageListResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static twilio.proxies.MessageListResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Twilio.MessageListResponsePager", mendixObject.getType()))
			return twilio.proxies.MessageListResponsePager.initialize(context, mendixObject);

		return new twilio.proxies.MessageListResponse(context, mendixObject);
	}

	public static twilio.proxies.MessageListResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilio.proxies.MessageListResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of first_page_uri
	 */
	public final String getfirst_page_uri()
	{
		return getfirst_page_uri(getContext());
	}

	/**
	 * @param context
	 * @return value of first_page_uri
	 */
	public final String getfirst_page_uri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.first_page_uri.toString());
	}

	/**
	 * Set value of first_page_uri
	 * @param first_page_uri
	 */
	public final void setfirst_page_uri(String first_page_uri)
	{
		setfirst_page_uri(getContext(), first_page_uri);
	}

	/**
	 * Set value of first_page_uri
	 * @param context
	 * @param first_page_uri
	 */
	public final void setfirst_page_uri(com.mendix.systemwideinterfaces.core.IContext context, String first_page_uri)
	{
		getMendixObject().setValue(context, MemberNames.first_page_uri.toString(), first_page_uri);
	}

	/**
	 * @return value of end
	 */
	public final Integer getend()
	{
		return getend(getContext());
	}

	/**
	 * @param context
	 * @return value of end
	 */
	public final Integer getend(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.end.toString());
	}

	/**
	 * Set value of end
	 * @param end
	 */
	public final void setend(Integer end)
	{
		setend(getContext(), end);
	}

	/**
	 * Set value of end
	 * @param context
	 * @param end
	 */
	public final void setend(com.mendix.systemwideinterfaces.core.IContext context, Integer end)
	{
		getMendixObject().setValue(context, MemberNames.end.toString(), end);
	}

	/**
	 * @return value of previous_page_uri
	 */
	public final String getprevious_page_uri()
	{
		return getprevious_page_uri(getContext());
	}

	/**
	 * @param context
	 * @return value of previous_page_uri
	 */
	public final String getprevious_page_uri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.previous_page_uri.toString());
	}

	/**
	 * Set value of previous_page_uri
	 * @param previous_page_uri
	 */
	public final void setprevious_page_uri(String previous_page_uri)
	{
		setprevious_page_uri(getContext(), previous_page_uri);
	}

	/**
	 * Set value of previous_page_uri
	 * @param context
	 * @param previous_page_uri
	 */
	public final void setprevious_page_uri(com.mendix.systemwideinterfaces.core.IContext context, String previous_page_uri)
	{
		getMendixObject().setValue(context, MemberNames.previous_page_uri.toString(), previous_page_uri);
	}

	/**
	 * @return value of uri
	 */
	public final String geturi()
	{
		return geturi(getContext());
	}

	/**
	 * @param context
	 * @return value of uri
	 */
	public final String geturi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.uri.toString());
	}

	/**
	 * Set value of uri
	 * @param uri
	 */
	public final void seturi(String uri)
	{
		seturi(getContext(), uri);
	}

	/**
	 * Set value of uri
	 * @param context
	 * @param uri
	 */
	public final void seturi(com.mendix.systemwideinterfaces.core.IContext context, String uri)
	{
		getMendixObject().setValue(context, MemberNames.uri.toString(), uri);
	}

	/**
	 * @return value of page_size
	 */
	public final Integer getpage_size()
	{
		return getpage_size(getContext());
	}

	/**
	 * @param context
	 * @return value of page_size
	 */
	public final Integer getpage_size(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.page_size.toString());
	}

	/**
	 * Set value of page_size
	 * @param page_size
	 */
	public final void setpage_size(Integer page_size)
	{
		setpage_size(getContext(), page_size);
	}

	/**
	 * Set value of page_size
	 * @param context
	 * @param page_size
	 */
	public final void setpage_size(com.mendix.systemwideinterfaces.core.IContext context, Integer page_size)
	{
		getMendixObject().setValue(context, MemberNames.page_size.toString(), page_size);
	}

	/**
	 * @return value of start
	 */
	public final Integer getstart()
	{
		return getstart(getContext());
	}

	/**
	 * @param context
	 * @return value of start
	 */
	public final Integer getstart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.start.toString());
	}

	/**
	 * Set value of start
	 * @param start
	 */
	public final void setstart(Integer start)
	{
		setstart(getContext(), start);
	}

	/**
	 * Set value of start
	 * @param context
	 * @param start
	 */
	public final void setstart(com.mendix.systemwideinterfaces.core.IContext context, Integer start)
	{
		getMendixObject().setValue(context, MemberNames.start.toString(), start);
	}

	/**
	 * @return value of next_page_uri
	 */
	public final String getnext_page_uri()
	{
		return getnext_page_uri(getContext());
	}

	/**
	 * @param context
	 * @return value of next_page_uri
	 */
	public final String getnext_page_uri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.next_page_uri.toString());
	}

	/**
	 * Set value of next_page_uri
	 * @param next_page_uri
	 */
	public final void setnext_page_uri(String next_page_uri)
	{
		setnext_page_uri(getContext(), next_page_uri);
	}

	/**
	 * Set value of next_page_uri
	 * @param context
	 * @param next_page_uri
	 */
	public final void setnext_page_uri(com.mendix.systemwideinterfaces.core.IContext context, String next_page_uri)
	{
		getMendixObject().setValue(context, MemberNames.next_page_uri.toString(), next_page_uri);
	}

	/**
	 * @return value of num_pages
	 */
	public final Integer getnum_pages()
	{
		return getnum_pages(getContext());
	}

	/**
	 * @param context
	 * @return value of num_pages
	 */
	public final Integer getnum_pages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.num_pages.toString());
	}

	/**
	 * Set value of num_pages
	 * @param num_pages
	 */
	public final void setnum_pages(Integer num_pages)
	{
		setnum_pages(getContext(), num_pages);
	}

	/**
	 * Set value of num_pages
	 * @param context
	 * @param num_pages
	 */
	public final void setnum_pages(com.mendix.systemwideinterfaces.core.IContext context, Integer num_pages)
	{
		getMendixObject().setValue(context, MemberNames.num_pages.toString(), num_pages);
	}

	/**
	 * @return value of total
	 */
	public final Integer gettotal()
	{
		return gettotal(getContext());
	}

	/**
	 * @param context
	 * @return value of total
	 */
	public final Integer gettotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.total.toString());
	}

	/**
	 * Set value of total
	 * @param total
	 */
	public final void settotal(Integer total)
	{
		settotal(getContext(), total);
	}

	/**
	 * Set value of total
	 * @param context
	 * @param total
	 */
	public final void settotal(com.mendix.systemwideinterfaces.core.IContext context, Integer total)
	{
		getMendixObject().setValue(context, MemberNames.total.toString(), total);
	}

	/**
	 * @return value of last_page_uri
	 */
	public final String getlast_page_uri()
	{
		return getlast_page_uri(getContext());
	}

	/**
	 * @param context
	 * @return value of last_page_uri
	 */
	public final String getlast_page_uri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.last_page_uri.toString());
	}

	/**
	 * Set value of last_page_uri
	 * @param last_page_uri
	 */
	public final void setlast_page_uri(String last_page_uri)
	{
		setlast_page_uri(getContext(), last_page_uri);
	}

	/**
	 * Set value of last_page_uri
	 * @param context
	 * @param last_page_uri
	 */
	public final void setlast_page_uri(com.mendix.systemwideinterfaces.core.IContext context, String last_page_uri)
	{
		getMendixObject().setValue(context, MemberNames.last_page_uri.toString(), last_page_uri);
	}

	/**
	 * @return value of page
	 */
	public final Integer getpage()
	{
		return getpage(getContext());
	}

	/**
	 * @param context
	 * @return value of page
	 */
	public final Integer getpage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.page.toString());
	}

	/**
	 * Set value of page
	 * @param page
	 */
	public final void setpage(Integer page)
	{
		setpage(getContext(), page);
	}

	/**
	 * Set value of page
	 * @param context
	 * @param page
	 */
	public final void setpage(com.mendix.systemwideinterfaces.core.IContext context, Integer page)
	{
		getMendixObject().setValue(context, MemberNames.page.toString(), page);
	}

	/**
	 * @return value of messages
	 */
	public final java.util.List<twilio.proxies.MessageResponse> getmessages() throws com.mendix.core.CoreException
	{
		return getmessages(getContext());
	}

	/**
	 * @param context
	 * @return value of messages
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<twilio.proxies.MessageResponse> getmessages(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<twilio.proxies.MessageResponse> result = new java.util.ArrayList<twilio.proxies.MessageResponse>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.messages.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(twilio.proxies.MessageResponse.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of messages
	 * @param messages
	 */
	public final void setmessages(java.util.List<twilio.proxies.MessageResponse> messages)
	{
		setmessages(getContext(), messages);
	}

	/**
	 * Set value of messages
	 * @param context
	 * @param messages
	 */
	public final void setmessages(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<twilio.proxies.MessageResponse> messages)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (twilio.proxies.MessageResponse proxyObject : messages)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.messages.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageListResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilio.proxies.MessageListResponse that = (twilio.proxies.MessageListResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Twilio.MessageListResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
