// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilio.proxies;

public class MessageResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Twilio.MessageResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		sid("sid"),
		to("to"),
		from("from"),
		body("body"),
		status("status"),
		uri("uri"),
		num_segments("num_segments"),
		num_media("num_media"),
		direction("direction"),
		error_code("error_code"),
		error_message("error_message"),
		date_created("date_created"),
		date_updated("date_updated"),
		date_sent("date_sent");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MessageResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Twilio.MessageResponse"));
	}

	protected MessageResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageResponseMendixObject)
	{
		if (messageResponseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Twilio.MessageResponse", messageResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Twilio.MessageResponse");

		this.messageResponseMendixObject = messageResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MessageResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twilio.proxies.MessageResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilio.proxies.MessageResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static twilio.proxies.MessageResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twilio.proxies.MessageResponse(context, mendixObject);
	}

	public static twilio.proxies.MessageResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilio.proxies.MessageResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of sid
	 */
	public final String getsid()
	{
		return getsid(getContext());
	}

	/**
	 * @param context
	 * @return value of sid
	 */
	public final String getsid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.sid.toString());
	}

	/**
	 * Set value of sid
	 * @param sid
	 */
	public final void setsid(String sid)
	{
		setsid(getContext(), sid);
	}

	/**
	 * Set value of sid
	 * @param context
	 * @param sid
	 */
	public final void setsid(com.mendix.systemwideinterfaces.core.IContext context, String sid)
	{
		getMendixObject().setValue(context, MemberNames.sid.toString(), sid);
	}

	/**
	 * @return value of to
	 */
	public final String getto()
	{
		return getto(getContext());
	}

	/**
	 * @param context
	 * @return value of to
	 */
	public final String getto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.to.toString());
	}

	/**
	 * Set value of to
	 * @param to
	 */
	public final void setto(String to)
	{
		setto(getContext(), to);
	}

	/**
	 * Set value of to
	 * @param context
	 * @param to
	 */
	public final void setto(com.mendix.systemwideinterfaces.core.IContext context, String to)
	{
		getMendixObject().setValue(context, MemberNames.to.toString(), to);
	}

	/**
	 * @return value of from
	 */
	public final String getfrom()
	{
		return getfrom(getContext());
	}

	/**
	 * @param context
	 * @return value of from
	 */
	public final String getfrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.from.toString());
	}

	/**
	 * Set value of from
	 * @param from
	 */
	public final void setfrom(String from)
	{
		setfrom(getContext(), from);
	}

	/**
	 * Set value of from
	 * @param context
	 * @param from
	 */
	public final void setfrom(com.mendix.systemwideinterfaces.core.IContext context, String from)
	{
		getMendixObject().setValue(context, MemberNames.from.toString(), from);
	}

	/**
	 * @return value of body
	 */
	public final String getbody()
	{
		return getbody(getContext());
	}

	/**
	 * @param context
	 * @return value of body
	 */
	public final String getbody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.body.toString());
	}

	/**
	 * Set value of body
	 * @param body
	 */
	public final void setbody(String body)
	{
		setbody(getContext(), body);
	}

	/**
	 * Set value of body
	 * @param context
	 * @param body
	 */
	public final void setbody(com.mendix.systemwideinterfaces.core.IContext context, String body)
	{
		getMendixObject().setValue(context, MemberNames.body.toString(), body);
	}

	/**
	 * @return value of status
	 */
	public final String getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final String getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.status.toString());
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(String status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, String status)
	{
		getMendixObject().setValue(context, MemberNames.status.toString(), status);
	}

	/**
	 * @return value of uri
	 */
	public final String geturi()
	{
		return geturi(getContext());
	}

	/**
	 * @param context
	 * @return value of uri
	 */
	public final String geturi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.uri.toString());
	}

	/**
	 * Set value of uri
	 * @param uri
	 */
	public final void seturi(String uri)
	{
		seturi(getContext(), uri);
	}

	/**
	 * Set value of uri
	 * @param context
	 * @param uri
	 */
	public final void seturi(com.mendix.systemwideinterfaces.core.IContext context, String uri)
	{
		getMendixObject().setValue(context, MemberNames.uri.toString(), uri);
	}

	/**
	 * @return value of num_segments
	 */
	public final Integer getnum_segments()
	{
		return getnum_segments(getContext());
	}

	/**
	 * @param context
	 * @return value of num_segments
	 */
	public final Integer getnum_segments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.num_segments.toString());
	}

	/**
	 * Set value of num_segments
	 * @param num_segments
	 */
	public final void setnum_segments(Integer num_segments)
	{
		setnum_segments(getContext(), num_segments);
	}

	/**
	 * Set value of num_segments
	 * @param context
	 * @param num_segments
	 */
	public final void setnum_segments(com.mendix.systemwideinterfaces.core.IContext context, Integer num_segments)
	{
		getMendixObject().setValue(context, MemberNames.num_segments.toString(), num_segments);
	}

	/**
	 * @return value of num_media
	 */
	public final Integer getnum_media()
	{
		return getnum_media(getContext());
	}

	/**
	 * @param context
	 * @return value of num_media
	 */
	public final Integer getnum_media(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.num_media.toString());
	}

	/**
	 * Set value of num_media
	 * @param num_media
	 */
	public final void setnum_media(Integer num_media)
	{
		setnum_media(getContext(), num_media);
	}

	/**
	 * Set value of num_media
	 * @param context
	 * @param num_media
	 */
	public final void setnum_media(com.mendix.systemwideinterfaces.core.IContext context, Integer num_media)
	{
		getMendixObject().setValue(context, MemberNames.num_media.toString(), num_media);
	}

	/**
	 * @return value of direction
	 */
	public final String getdirection()
	{
		return getdirection(getContext());
	}

	/**
	 * @param context
	 * @return value of direction
	 */
	public final String getdirection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.direction.toString());
	}

	/**
	 * Set value of direction
	 * @param direction
	 */
	public final void setdirection(String direction)
	{
		setdirection(getContext(), direction);
	}

	/**
	 * Set value of direction
	 * @param context
	 * @param direction
	 */
	public final void setdirection(com.mendix.systemwideinterfaces.core.IContext context, String direction)
	{
		getMendixObject().setValue(context, MemberNames.direction.toString(), direction);
	}

	/**
	 * @return value of error_code
	 */
	public final String geterror_code()
	{
		return geterror_code(getContext());
	}

	/**
	 * @param context
	 * @return value of error_code
	 */
	public final String geterror_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.error_code.toString());
	}

	/**
	 * Set value of error_code
	 * @param error_code
	 */
	public final void seterror_code(String error_code)
	{
		seterror_code(getContext(), error_code);
	}

	/**
	 * Set value of error_code
	 * @param context
	 * @param error_code
	 */
	public final void seterror_code(com.mendix.systemwideinterfaces.core.IContext context, String error_code)
	{
		getMendixObject().setValue(context, MemberNames.error_code.toString(), error_code);
	}

	/**
	 * @return value of error_message
	 */
	public final String geterror_message()
	{
		return geterror_message(getContext());
	}

	/**
	 * @param context
	 * @return value of error_message
	 */
	public final String geterror_message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.error_message.toString());
	}

	/**
	 * Set value of error_message
	 * @param error_message
	 */
	public final void seterror_message(String error_message)
	{
		seterror_message(getContext(), error_message);
	}

	/**
	 * Set value of error_message
	 * @param context
	 * @param error_message
	 */
	public final void seterror_message(com.mendix.systemwideinterfaces.core.IContext context, String error_message)
	{
		getMendixObject().setValue(context, MemberNames.error_message.toString(), error_message);
	}

	/**
	 * @return value of date_created
	 */
	public final String getdate_created()
	{
		return getdate_created(getContext());
	}

	/**
	 * @param context
	 * @return value of date_created
	 */
	public final String getdate_created(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.date_created.toString());
	}

	/**
	 * Set value of date_created
	 * @param date_created
	 */
	public final void setdate_created(String date_created)
	{
		setdate_created(getContext(), date_created);
	}

	/**
	 * Set value of date_created
	 * @param context
	 * @param date_created
	 */
	public final void setdate_created(com.mendix.systemwideinterfaces.core.IContext context, String date_created)
	{
		getMendixObject().setValue(context, MemberNames.date_created.toString(), date_created);
	}

	/**
	 * @return value of date_updated
	 */
	public final String getdate_updated()
	{
		return getdate_updated(getContext());
	}

	/**
	 * @param context
	 * @return value of date_updated
	 */
	public final String getdate_updated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.date_updated.toString());
	}

	/**
	 * Set value of date_updated
	 * @param date_updated
	 */
	public final void setdate_updated(String date_updated)
	{
		setdate_updated(getContext(), date_updated);
	}

	/**
	 * Set value of date_updated
	 * @param context
	 * @param date_updated
	 */
	public final void setdate_updated(com.mendix.systemwideinterfaces.core.IContext context, String date_updated)
	{
		getMendixObject().setValue(context, MemberNames.date_updated.toString(), date_updated);
	}

	/**
	 * @return value of date_sent
	 */
	public final String getdate_sent()
	{
		return getdate_sent(getContext());
	}

	/**
	 * @param context
	 * @return value of date_sent
	 */
	public final String getdate_sent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.date_sent.toString());
	}

	/**
	 * Set value of date_sent
	 * @param date_sent
	 */
	public final void setdate_sent(String date_sent)
	{
		setdate_sent(getContext(), date_sent);
	}

	/**
	 * Set value of date_sent
	 * @param context
	 * @param date_sent
	 */
	public final void setdate_sent(com.mendix.systemwideinterfaces.core.IContext context, String date_sent)
	{
		getMendixObject().setValue(context, MemberNames.date_sent.toString(), date_sent);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilio.proxies.MessageResponse that = (twilio.proxies.MessageResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Twilio.MessageResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
