// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilio.proxies;

public class OutgoingMessageRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject outgoingMessageRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Twilio.OutgoingMessageRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		From("From"),
		To("To"),
		Body("Body"),
		OutgoingMessageRequest_ResponseException("Twilio.OutgoingMessageRequest_ResponseException"),
		OutgoingMessageRequest_PhoneNr("Twilio.OutgoingMessageRequest_PhoneNr");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingMessageRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Twilio.OutgoingMessageRequest"));
	}

	protected OutgoingMessageRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingMessageRequestMendixObject)
	{
		if (outgoingMessageRequestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Twilio.OutgoingMessageRequest", outgoingMessageRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Twilio.OutgoingMessageRequest");

		this.outgoingMessageRequestMendixObject = outgoingMessageRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OutgoingMessageRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twilio.proxies.OutgoingMessageRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilio.proxies.OutgoingMessageRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static twilio.proxies.OutgoingMessageRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Twilio.OutgoingMessageRequestWithMediaURL", mendixObject.getType()))
			return twilio.proxies.OutgoingMessageRequestWithMediaURL.initialize(context, mendixObject);

		return new twilio.proxies.OutgoingMessageRequest(context, mendixObject);
	}

	public static twilio.proxies.OutgoingMessageRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilio.proxies.OutgoingMessageRequest.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of From
	 */
	public final String getFrom()
	{
		return getFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of From
	 */
	public final String getFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.From.toString());
	}

	/**
	 * Set value of From
	 * @param from
	 */
	public final void setFrom(String from)
	{
		setFrom(getContext(), from);
	}

	/**
	 * Set value of From
	 * @param context
	 * @param from
	 */
	public final void setFrom(com.mendix.systemwideinterfaces.core.IContext context, String from)
	{
		getMendixObject().setValue(context, MemberNames.From.toString(), from);
	}

	/**
	 * @return value of To
	 */
	public final String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return value of Body
	 */
	public final String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of OutgoingMessageRequest_ResponseException
	 */
	public final twilio.proxies.ResponseException getOutgoingMessageRequest_ResponseException() throws com.mendix.core.CoreException
	{
		return getOutgoingMessageRequest_ResponseException(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingMessageRequest_ResponseException
	 */
	public final twilio.proxies.ResponseException getOutgoingMessageRequest_ResponseException(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		twilio.proxies.ResponseException result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingMessageRequest_ResponseException.toString());
		if (identifier != null)
			result = twilio.proxies.ResponseException.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingMessageRequest_ResponseException
	 * @param outgoingmessagerequest_responseexception
	 */
	public final void setOutgoingMessageRequest_ResponseException(twilio.proxies.ResponseException outgoingmessagerequest_responseexception)
	{
		setOutgoingMessageRequest_ResponseException(getContext(), outgoingmessagerequest_responseexception);
	}

	/**
	 * Set value of OutgoingMessageRequest_ResponseException
	 * @param context
	 * @param outgoingmessagerequest_responseexception
	 */
	public final void setOutgoingMessageRequest_ResponseException(com.mendix.systemwideinterfaces.core.IContext context, twilio.proxies.ResponseException outgoingmessagerequest_responseexception)
	{
		if (outgoingmessagerequest_responseexception == null)
			getMendixObject().setValue(context, MemberNames.OutgoingMessageRequest_ResponseException.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingMessageRequest_ResponseException.toString(), outgoingmessagerequest_responseexception.getMendixObject().getId());
	}

	/**
	 * @return value of OutgoingMessageRequest_PhoneNr
	 */
	public final twilio.proxies.Phonenumber getOutgoingMessageRequest_PhoneNr() throws com.mendix.core.CoreException
	{
		return getOutgoingMessageRequest_PhoneNr(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingMessageRequest_PhoneNr
	 */
	public final twilio.proxies.Phonenumber getOutgoingMessageRequest_PhoneNr(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		twilio.proxies.Phonenumber result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingMessageRequest_PhoneNr.toString());
		if (identifier != null)
			result = twilio.proxies.Phonenumber.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingMessageRequest_PhoneNr
	 * @param outgoingmessagerequest_phonenr
	 */
	public final void setOutgoingMessageRequest_PhoneNr(twilio.proxies.Phonenumber outgoingmessagerequest_phonenr)
	{
		setOutgoingMessageRequest_PhoneNr(getContext(), outgoingmessagerequest_phonenr);
	}

	/**
	 * Set value of OutgoingMessageRequest_PhoneNr
	 * @param context
	 * @param outgoingmessagerequest_phonenr
	 */
	public final void setOutgoingMessageRequest_PhoneNr(com.mendix.systemwideinterfaces.core.IContext context, twilio.proxies.Phonenumber outgoingmessagerequest_phonenr)
	{
		if (outgoingmessagerequest_phonenr == null)
			getMendixObject().setValue(context, MemberNames.OutgoingMessageRequest_PhoneNr.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingMessageRequest_PhoneNr.toString(), outgoingmessagerequest_phonenr.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return outgoingMessageRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilio.proxies.OutgoingMessageRequest that = (twilio.proxies.OutgoingMessageRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Twilio.OutgoingMessageRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
