// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilio.proxies;

public class OutgoingMessageRequest_2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject outgoingMessageRequest_2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Twilio.OutgoingMessageRequest_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		From("From"),
		To("To"),
		Body("Body"),
		StatusCallback("StatusCallback"),
		ApplicationSid("ApplicationSid");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingMessageRequest_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Twilio.OutgoingMessageRequest_2"));
	}

	protected OutgoingMessageRequest_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingMessageRequest_2MendixObject)
	{
		if (outgoingMessageRequest_2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Twilio.OutgoingMessageRequest_2", outgoingMessageRequest_2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Twilio.OutgoingMessageRequest_2");

		this.outgoingMessageRequest_2MendixObject = outgoingMessageRequest_2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OutgoingMessageRequest_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twilio.proxies.OutgoingMessageRequest_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilio.proxies.OutgoingMessageRequest_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static twilio.proxies.OutgoingMessageRequest_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twilio.proxies.OutgoingMessageRequest_2(context, mendixObject);
	}

	public static twilio.proxies.OutgoingMessageRequest_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilio.proxies.OutgoingMessageRequest_2.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of From
	 */
	public final String getFrom()
	{
		return getFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of From
	 */
	public final String getFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.From.toString());
	}

	/**
	 * Set value of From
	 * @param from
	 */
	public final void setFrom(String from)
	{
		setFrom(getContext(), from);
	}

	/**
	 * Set value of From
	 * @param context
	 * @param from
	 */
	public final void setFrom(com.mendix.systemwideinterfaces.core.IContext context, String from)
	{
		getMendixObject().setValue(context, MemberNames.From.toString(), from);
	}

	/**
	 * @return value of To
	 */
	public final String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return value of Body
	 */
	public final String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of StatusCallback
	 */
	public final String getStatusCallback()
	{
		return getStatusCallback(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusCallback
	 */
	public final String getStatusCallback(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.StatusCallback.toString());
	}

	/**
	 * Set value of StatusCallback
	 * @param statuscallback
	 */
	public final void setStatusCallback(String statuscallback)
	{
		setStatusCallback(getContext(), statuscallback);
	}

	/**
	 * Set value of StatusCallback
	 * @param context
	 * @param statuscallback
	 */
	public final void setStatusCallback(com.mendix.systemwideinterfaces.core.IContext context, String statuscallback)
	{
		getMendixObject().setValue(context, MemberNames.StatusCallback.toString(), statuscallback);
	}

	/**
	 * @return value of ApplicationSid
	 */
	public final String getApplicationSid()
	{
		return getApplicationSid(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationSid
	 */
	public final String getApplicationSid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ApplicationSid.toString());
	}

	/**
	 * Set value of ApplicationSid
	 * @param applicationsid
	 */
	public final void setApplicationSid(String applicationsid)
	{
		setApplicationSid(getContext(), applicationsid);
	}

	/**
	 * Set value of ApplicationSid
	 * @param context
	 * @param applicationsid
	 */
	public final void setApplicationSid(com.mendix.systemwideinterfaces.core.IContext context, String applicationsid)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationSid.toString(), applicationsid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return outgoingMessageRequest_2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilio.proxies.OutgoingMessageRequest_2 that = (twilio.proxies.OutgoingMessageRequest_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Twilio.OutgoingMessageRequest_2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
