// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilio.proxies;

public class OutgoingMessageRequestWithMediaURL extends twilio.proxies.OutgoingMessageRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Twilio.OutgoingMessageRequestWithMediaURL";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MediaUrl("MediaUrl"),
		From("From"),
		To("To"),
		Body("Body"),
		OutgoingMessageRequest_ResponseException("Twilio.OutgoingMessageRequest_ResponseException"),
		OutgoingMessageRequest_PhoneNr("Twilio.OutgoingMessageRequest_PhoneNr");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingMessageRequestWithMediaURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Twilio.OutgoingMessageRequestWithMediaURL"));
	}

	protected OutgoingMessageRequestWithMediaURL(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingMessageRequestWithMediaURLMendixObject)
	{
		super(context, outgoingMessageRequestWithMediaURLMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Twilio.OutgoingMessageRequestWithMediaURL", outgoingMessageRequestWithMediaURLMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Twilio.OutgoingMessageRequestWithMediaURL");
	}

	/**
	 * @deprecated Use 'OutgoingMessageRequestWithMediaURL.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twilio.proxies.OutgoingMessageRequestWithMediaURL initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilio.proxies.OutgoingMessageRequestWithMediaURL.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static twilio.proxies.OutgoingMessageRequestWithMediaURL initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twilio.proxies.OutgoingMessageRequestWithMediaURL(context, mendixObject);
	}

	public static twilio.proxies.OutgoingMessageRequestWithMediaURL load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilio.proxies.OutgoingMessageRequestWithMediaURL.initialize(context, mendixObject);
	}

	/**
	 * @return value of MediaUrl
	 */
	public final String getMediaUrl()
	{
		return getMediaUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of MediaUrl
	 */
	public final String getMediaUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.MediaUrl.toString());
	}

	/**
	 * Set value of MediaUrl
	 * @param mediaurl
	 */
	public final void setMediaUrl(String mediaurl)
	{
		setMediaUrl(getContext(), mediaurl);
	}

	/**
	 * Set value of MediaUrl
	 * @param context
	 * @param mediaurl
	 */
	public final void setMediaUrl(com.mendix.systemwideinterfaces.core.IContext context, String mediaurl)
	{
		getMendixObject().setValue(context, MemberNames.MediaUrl.toString(), mediaurl);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilio.proxies.OutgoingMessageRequestWithMediaURL that = (twilio.proxies.OutgoingMessageRequestWithMediaURL) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Twilio.OutgoingMessageRequestWithMediaURL";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
