// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilio.proxies;

public class Phonenumber
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject phonenumberMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Twilio.Phonenumber";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nr("Nr"),
		AccountSID("AccountSID"),
		Token("Token");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Phonenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Twilio.Phonenumber"));
	}

	protected Phonenumber(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject phonenumberMendixObject)
	{
		if (phonenumberMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Twilio.Phonenumber", phonenumberMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Twilio.Phonenumber");

		this.phonenumberMendixObject = phonenumberMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Phonenumber.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twilio.proxies.Phonenumber initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twilio.proxies.Phonenumber.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static twilio.proxies.Phonenumber initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twilio.proxies.Phonenumber(context, mendixObject);
	}

	public static twilio.proxies.Phonenumber load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twilio.proxies.Phonenumber.initialize(context, mendixObject);
	}

	public static java.util.List<twilio.proxies.Phonenumber> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<twilio.proxies.Phonenumber> result = new java.util.ArrayList<twilio.proxies.Phonenumber>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Twilio.Phonenumber" + xpathConstraint))
			result.add(twilio.proxies.Phonenumber.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Nr
	 */
	public final String getNr()
	{
		return getNr(getContext());
	}

	/**
	 * @param context
	 * @return value of Nr
	 */
	public final String getNr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Nr.toString());
	}

	/**
	 * Set value of Nr
	 * @param nr
	 */
	public final void setNr(String nr)
	{
		setNr(getContext(), nr);
	}

	/**
	 * Set value of Nr
	 * @param context
	 * @param nr
	 */
	public final void setNr(com.mendix.systemwideinterfaces.core.IContext context, String nr)
	{
		getMendixObject().setValue(context, MemberNames.Nr.toString(), nr);
	}

	/**
	 * @return value of AccountSID
	 */
	public final String getAccountSID()
	{
		return getAccountSID(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountSID
	 */
	public final String getAccountSID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.AccountSID.toString());
	}

	/**
	 * Set value of AccountSID
	 * @param accountsid
	 */
	public final void setAccountSID(String accountsid)
	{
		setAccountSID(getContext(), accountsid);
	}

	/**
	 * Set value of AccountSID
	 * @param context
	 * @param accountsid
	 */
	public final void setAccountSID(com.mendix.systemwideinterfaces.core.IContext context, String accountsid)
	{
		getMendixObject().setValue(context, MemberNames.AccountSID.toString(), accountsid);
	}

	/**
	 * @return value of Token
	 */
	public final String getToken()
	{
		return getToken(getContext());
	}

	/**
	 * @param context
	 * @return value of Token
	 */
	public final String getToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Token.toString());
	}

	/**
	 * Set value of Token
	 * @param token
	 */
	public final void setToken(String token)
	{
		setToken(getContext(), token);
	}

	/**
	 * Set value of Token
	 * @param context
	 * @param token
	 */
	public final void setToken(com.mendix.systemwideinterfaces.core.IContext context, String token)
	{
		getMendixObject().setValue(context, MemberNames.Token.toString(), token);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return phonenumberMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twilio.proxies.Phonenumber that = (twilio.proxies.Phonenumber) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Twilio.Phonenumber";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
