// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilio.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Twilio module
	public static twilio.proxies.OutgoingMessageRequest dSO_OutgoingMessageRequest(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "Twilio.DSO_OutgoingMessageRequest", params);
			return result == null ? null : twilio.proxies.OutgoingMessageRequest.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Account_Commit(IContext context, twilio.proxies.Phonenumber _account)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Account", _account == null ? null : _account.getMendixObject());
			Core.execute(context, "Twilio.IVK_Account_Commit", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Account_Selected(IContext context, twilio.proxies.Phonenumber _account)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Account", _account == null ? null : _account.getMendixObject());
			Core.execute(context, "Twilio.IVK_Account_Selected", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SendOutgoingMessage(IContext context, twilio.proxies.OutgoingMessageRequest _outgoingMessageRequest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("OutgoingMessageRequest", _outgoingMessageRequest == null ? null : _outgoingMessageRequest.getMendixObject());
			Core.execute(context, "Twilio.IVK_SendOutgoingMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean messageResponsePager_HasNext(IContext context, twilio.proxies.MessageListResponsePager _messageListResonsePager)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MessageListResonsePager", _messageListResonsePager == null ? null : _messageListResonsePager.getMendixObject());
			return (Boolean)Core.execute(context, "Twilio.MessageResponsePager_HasNext", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}