// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilioconnector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TwilioConnector module

	public static String getAccount_SID()
	{
		return (String)Core.getConfiguration().getConstantValue("TwilioConnector.Account_SID");
	}

	public static String getAccount_Token()
	{
		return (String)Core.getConfiguration().getConstantValue("TwilioConnector.Account_Token");
	}

	public static String getTestAccount_SID()
	{
		return (String)Core.getConfiguration().getConstantValue("TwilioConnector.TestAccount_SID");
	}

	public static String getTestAccount_Token()
	{
		return (String)Core.getConfiguration().getConstantValue("TwilioConnector.TestAccount_Token");
	}
}