// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twilio.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Twilio module

	public static String getapiVersion()
	{
		return (String)Core.getConfiguration().getConstantValue("Twilio.apiVersion");
	}

	public static String getbaseURL()
	{
		return (String)Core.getConfiguration().getConstantValue("Twilio.baseURL");
	}
}