// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twilio.actions;

import java.io.StringReader;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.InputSource;
import twilio.proxies.ResponseException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ParseResponseExceptionStringToObject extends CustomJavaAction<IMendixObject>
{
	private String Parameter;

	public ParseResponseExceptionStringToObject(IContext context, String Parameter)
	{
		super(context);
		this.Parameter = Parameter;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		 DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
		 DocumentBuilder builder = factory.newDocumentBuilder();
		 InputSource is = new InputSource(new StringReader(this.Parameter));
		 Document XMLDocument =  builder.parse(is);
		
		 ResponseException newResponseException = new ResponseException(this.getContext());
		 
		 Element rootElement = XMLDocument.getDocumentElement();
		 newResponseException.setStatus(Integer.parseInt(rootElement.getElementsByTagName("Status").item(0).getChildNodes().item(0).getNodeValue()));
		 newResponseException.setCode(Integer.parseInt(rootElement.getElementsByTagName("Code").item(0).getChildNodes().item(0).getNodeValue()));
		 newResponseException.setMessage(rootElement.getElementsByTagName("Message").item(0).getChildNodes().item(0).getNodeValue());
		 newResponseException.setMoreInfo(rootElement.getElementsByTagName("MoreInfo").item(0).getChildNodes().item(0).getNodeValue());
		 
		 return newResponseException.getMendixObject();
		
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ParseResponseExceptionStringToObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
